global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'quotes-aggregator-dev'

scrape_configs:
  - job_name: 'quotes-aggregator'
    static_configs:
      - targets: ['quotes-aggregator:3000']
    metrics_path: /metrics
    scrape_interval: 10s
